# Generated by Django 4.0.4 on 2022-07-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='data',
        ),
    ]
